server:
  port: 8006
spring:
  application:
    name: springcloud-oauth
#  rabbitmq:
#    host: ${RABBIT_MQ_HOST:localhost}
#    port: ${RABBIT_MQ_PORT:5672}
#    username: ${RABBIT_MQ_USERNAME:guest}
#    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
      ##password: ${REDIS_PASSWORD:}
#  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/sc_auth
#    username: ${POSTGRES_USERNAME:postgres}
#    password: ${POSTGRES_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basedata?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: taohui1996

#  zipkin:
#    enabled: true
#    sender:
#      type: rabbit
#  sleuth:
#    sampler:
#      probability: 1.0

#  mvc:
#    throw-exception-if-no-handler-found: true

    #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    com.springboot.auth: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true