server:
  port: 8002
spring:
  application:
    name: springcloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
