server:
  port: 8000

spring:
  application:
    name: authorization-server
#  rabbitmq:
#    host: ${RABBIT_MQ_HOST:localhost}
#    port: ${RABBIT_MQ_PORT:5672}
#    username: ${RABBIT_MQ_USERNAME:guest}
#    password: ${RABBIT_MQ_PASSWORD:guest}
#  redis:
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
    ##password: ${REDIS_PASSWORD:}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:3306}/basedata
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:taohui1996}
    driver-class-name: org.postgresql.Driver
#  boot:
#    admin:
#      url: http://${BOOT_ADMIN_HOST:localhost}:${BOOT_ADMIN_PORT:8022}
#  zipkin:
#    baseUrl: http://localhost:8091
  security:
    oauth2:
      jwt:
        signingKey: 123456

#logging:
#  level:
#    org.springframework.web: debug
#    org.springframework.security: DEBUG
#    com.springboot.auth: DEBUG
#    org.apache.ibatis: debug
#    java.sql.PreparedStatement: debug
#  path: logs/
#  file:
#    max-size: 1GB

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapping/**/*.xml
  type-aliases-package: com.th.**.model


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/